assert.exception(function () {
  $0
});
